/* Reading Rocket — image bundler.
   Scans the source for every emoji we render, downloads the matching OpenMoji
   illustration (consistent, ink-outlined, identical on every device), and
   writes:
     img/openmoji/<SEQ>.svg   one file per emoji
     js/imgmap.js             window.RR.IMGMAP = { "🐱": "1F431", ... }
   Run:  node tools/fetch-images.js
   Re-run any time you add emoji to the word lists — it only fetches new ones. */

const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'img', 'openmoji');
fs.mkdirSync(OUT, { recursive: true });

/* Matches keycaps, single pictographs (with optional skin tone / VS), and
   ZWJ sequences. Good enough for our curated content set. */
const EMOJI_RE = /[#*0-9]️?⃣|\p{Extended_Pictographic}(?:[\u{1F3FB}-\u{1F3FF}]|️)?(?:‍\p{Extended_Pictographic}(?:[\u{1F3FB}-\u{1F3FF}]|️)?)*/gu;

/* Collect every emoji used across the source. */
const files = fs.readdirSync(path.join(ROOT, 'js')).filter(f => f.endsWith('.js') && f !== 'imgmap.js');
const found = new Set();
for (const f of files) {
  const txt = fs.readFileSync(path.join(ROOT, 'js', f), 'utf8');
  for (const m of txt.matchAll(EMOJI_RE)) found.add(m[0]);
}

function seqOf(emoji) {
  return [...emoji]
    .map(c => c.codePointAt(0))
    .filter(cp => cp !== 0xFE0F)                 /* OpenMoji drops the VS16 */
    .map(cp => cp.toString(16).toUpperCase().padStart(4, '0'))
    .join('-');
}

function download(url) {
  return new Promise((resolve) => {
    https.get(url, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return resolve(download(res.headers.location));
      }
      if (res.statusCode !== 200) { res.resume(); return resolve(null); }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', () => resolve(null));
  });
}

const CDN = seq => `https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/${seq}.svg`;

async function run() {
  const emojis = [...found];
  const map = {};
  let got = 0, missing = [];

  /* small concurrency pool */
  let i = 0;
  async function worker() {
    while (i < emojis.length) {
      const e = emojis[i++];
      const seq = seqOf(e);
      const file = path.join(OUT, seq + '.svg');
      if (fs.existsSync(file)) { map[e] = seq; got++; continue; }
      let data = await download(CDN(seq));
      /* retry keeping the VS16 for the few emoji OpenMoji names that way */
      if (!data && /️/.test(e)) {
        const altSeq = [...e].map(c => c.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')).join('-');
        data = await download(CDN(altSeq));
        if (data) { fs.writeFileSync(path.join(OUT, altSeq + '.svg'), data); map[e] = altSeq; got++; continue; }
      }
      if (data) { fs.writeFileSync(file, data); map[e] = seq; got++; }
      else missing.push(e + ' (' + seq + ')');
    }
  }
  await Promise.all(Array.from({ length: 10 }, worker));

  /* stable, sorted manifest */
  const sorted = {};
  Object.keys(map).sort().forEach(k => sorted[k] = map[k]);
  const js = '/* AUTO-GENERATED by tools/fetch-images.js — do not edit by hand. */\n' +
    'window.RR = window.RR || {};\nRR.IMGMAP = ' + JSON.stringify(sorted, null, 0) + ';\n';
  fs.writeFileSync(path.join(ROOT, 'js', 'imgmap.js'), js);

  console.log(`✅ ${got} images ready in img/openmoji/  (${Object.keys(sorted).length} mapped)`);
  if (missing.length) console.log(`⚠️  ${missing.length} not in OpenMoji (will fall back to system emoji):\n   ` + missing.join('\n   '));
}

run();
